# Generated by Django 5.2.12 on 2026-03-24 08:36

import django.db.models.deletion
import handwriting_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('survey_done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('handedness', models.CharField(choices=[('right', 'Right'), ('left', 'Left'), ('both', 'Both')], max_length=10)),
                ('native_language', models.CharField(blank=True, max_length=50)),
                ('hometown', models.CharField(blank=True, max_length=100)),
                ('mother_tongue', models.CharField(blank=True, max_length=10)),
                ('education_level', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('writing_fluency', models.CharField(blank=True, max_length=50)),
                ('reading_fluency', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='handwriting_app.participant')),
            ],
        ),
        migrations.CreateModel(
            name='HandwritingSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('vowels', 'Vowels'), ('consonants', 'Consonants'), ('conjuncts', 'Conjuncts'), ('kagunitas', 'Kagunitas')], max_length=20)),
                ('character', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=handwriting_app.models.handwriting_upload_path)),
                ('stroke_data', models.JSONField()),
                ('time_taken', models.IntegerField(help_text='Time taken in milliseconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='handwriting_app.participant')),
            ],
            options={
                'ordering': ['task', 'character', 'created_at'],
                'unique_together': {('participant', 'task', 'character')},
            },
        ),
    ]
